# -*- coding: utf-8 -*-
"""LAB_02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GB8yDde53wX6LfnMfN_3oGybZMgQwaMP

# **Lists**
"""

# create a list
num = [1,2,3,4,5,6,7,8,9,10]
print(f"List: {num}")

# find the maximum value
max_val = max(num)
print(f" Max value : {max_val}")

# find the minimum value
min_val = min(num)
print(f' Min value : {min_val}')

# sum of all values
sum_vals = sum(num)
print(f' Sum : {sum_vals}')

# add 11 in list
num.append(11)
print(f'New List: {num}')

# remove 2 from the list
num.remove(2)
print(f'Update list : {num}')

# assending order
num.sort()
print(f'Assending order : {num}')

# decending order
num.sort(reverse=True)
print(f'Decending order : {num}')

"""# **Tuple**"""

# create a tuple with 5 fruits name
fruits = ('Apple','Banana','Cherry','Mango','Orange')
print(f'Fruits: {fruits}')

# Modification
# fruits.append('Grapes')
# print(f'New fruits: {fruits}')

#convert tuple into list
List = list(fruits)
List.append('Grapes')
fruits = tuple(List)
print(f'New fruits: {fruits}')

"""# **Sets**"""

# create a set
std_01 = {"Asif","Hassam","Yawar"}
std_02 = {"Rehman","Azan","Bilal"}
print(f' BSE 6C Students: {std_01}')
print(f' BSE 6B Students: {std_02}')

"""# **Dictionaries**"""

# create a dictionary of student
std_info = {
    'name': 'Yawar Hussain',
    'reg_no': 'SP23-BSE-122',
    'section': 'BSE 6C',
    'Age':22,
    'Gender':'Male'
}
# change the value of age
std_info['Age'] = 23

for key,value in std_info.items():
  print(f'{key} : {value}')

"""# **Numpy**

# **Matlab**
"""