# -*- coding: utf-8 -*-
"""ResultReproduce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pP4w8gQtic2XghdauTEOJYM5ntEiL3JH

# **Numpy**
"""

import numpy as np

# create 1D array
arr = np.arange(1,41)
print(f' 1D Array {arr}\n')

# Reshape to 4x5 matrix
matrix = arr.reshape(4,10)
print(f'{matrix}')

#Mean Medium Std
print(f'Mean : {np.mean(arr)}')
print(f'Medium : {np.median(arr)}')
print(f'Standard Deviation {np.std(arr)}')

#Element-wise Operation
arr2 = np.arange(31,51)
print(f'Addition: {arr2}')

"""# **Matplotlib**"""

import matplotlib.pyplot as plt
# List Plot
list_01 = list(range(1,21))
list_02 = [i**2 for i in list_01]
plt.plot(list_01,list_02)
plt.title('Numbers Vs Squares')
plt.xlabel('Names')
plt.ylabel('Squares')
plt.show()

# Bar Chart
students = ["Hassam","Asif","Bilal","Rehman","Azan","Yawar"]
marks = [91,89,96,92,86,84]
plt.bar(students,marks)
plt.title('Students Vs Marks')
plt.xlabel('Student Marks')
plt.ylabel('Marks')
plt.show()

# pi Bar
laptops = ["Dell","Hp","Thinkpad","Mac"]
rating = [5.6,6,7.4,8]
plt.pie(rating,labels=laptops,autopct = '%1.1f%%')
plt.title('Laptop Rating')

plt.show()