# -*- coding: utf-8 -*-
"""VirusShare.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Wm7olxUiHCitJcNCEALn-DBLB5cJnfv
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Pre-processing
file_path = '/content/sample_data/mnist_test.csv'
mnist_test_df = pd.read_csv(file_path)

# Separate features and labels
X = mnist_test_df.iloc[:, 1:].values  # pixel values
y = mnist_test_df.iloc[:, 0].values   # digit labels

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Apply KNN
model = KNeighborsClassifier(n_neighbors=3)
model.fit(X_train, y_train)

y_train_pred = model.predict(X_train)
y_test_pred = model.predict(X_test)


train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_test_pred)

# Output results
print(f"Training Accuracy: {train_accuracy:.4f}")
print(f"Testing Accuracy: {test_accuracy:.4f}")